import { useState, useEffect, useMemo } from "react";
import { Layout } from "@/components/Layout";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { PeriodFilter } from "@/components/PeriodFilter";
import { usePeriod } from "@/contexts/PeriodContext";
import { formatCurrency } from "@/data/expensesData";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter
} from "@/components/ui/dialog";
import {
  RefreshCw, FileDown, Search, Calendar as CalendarIcon,
  ChevronDown, ChevronRight, Sparkles, AlertTriangle,
  Trash2, Edit2, History, Bot, User, X, FileText
} from "lucide-react";
import { format, endOfMonth, parseISO } from "date-fns";
import { cn } from "@/lib/utils";
import { AccountingAuditService } from "@/services/AccountingAuditService";

interface AccountingEntry {
  id: string;
  entry_number: number;
  entry_date: string;
  competence_date: string;
  description: string;
  history: string | null;
  document_number: string | null;
  document_type: string | null;
  entry_type: string;
  total_debit: number;
  total_credit: number;
  balanced: boolean;
  ai_generated: boolean;
  ai_confidence: number | null;
  ai_model: string | null;
  internal_code: string | null;
  reference_type: string | null;
  reference_id: string | null;
  created_at: string;
  lines: Array<{
    id: string;
    account_id: string;
    account_code: string;
    account_name: string;
    debit: number;
    credit: number;
    description: string | null;
  }>;
}

interface EditingLine {
  entry_id: string;
  line_id: string;
  account_code: string;
  account_name: string;
  account_id: string;
  debit: number;
  credit: number;
  description: string | null;
}

const LivroDiario = () => {
  const { selectedYear, selectedMonth } = usePeriod();
  const [loading, setLoading] = useState(true);
  const [entries, setEntries] = useState<AccountingEntry[]>([]);
  const [chartOfAccounts, setChartOfAccounts] = useState<any[]>([]);
  const [expandedEntries, setExpandedEntries] = useState<Set<string>>(new Set());
  const [selectedEntries, setSelectedEntries] = useState<Set<string>>(new Set());
  const [searchTerm, setSearchTerm] = useState('');
  const [filterOrigin, setFilterOrigin] = useState<'all' | 'auto' | 'manual'>('all');

  // Estados de edição e auditoria
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [editingLine, setEditingLine] = useState<EditingLine | null>(null);
  const [historyDialogOpen, setHistoryDialogOpen] = useState(false);
  const [auditHistory, setAuditHistory] = useState<any[]>([]);
  const [selectedEntryId, setSelectedEntryId] = useState<string>('');

  const [stats, setStats] = useState({
    total: 0,
    autoGenerated: 0,
    manual: 0,
    totalDebit: 0,
    totalCredit: 0,
  });

  // Carregar plano de contas para edição
  const loadChartOfAccounts = async () => {
    try {
      const { data, error } = await supabase
        .from('chart_of_accounts')
        .select('id, code, name, type')
        .order('code');

      if (error) throw error;
      setChartOfAccounts(data || []);
    } catch (error: any) {
      console.error('Erro ao carregar plano de contas:', error?.message || error);
    }
  };

  // Carregar lançamentos baseado no período selecionado
  const loadEntries = async () => {
    setLoading(true);
    try {
      const startDate = format(new Date(selectedYear, selectedMonth - 1, 1), 'yyyy-MM-dd');
      const endDate = format(endOfMonth(new Date(selectedYear, selectedMonth - 1)), 'yyyy-MM-dd');

      const { data, error } = await supabase
        .from("accounting_entries")
        .select(`
          *,
          accounting_entry_items(
            id,
            account_id,
            debit,
            credit,
            description,
            chart_of_accounts(code, name)
          )
        `)
        .gte('entry_date', startDate)
        .lte('entry_date', endDate)
        .order('entry_date', { ascending: false })
        .limit(500);

      if (error) throw error;

      const formattedEntries: AccountingEntry[] = (data || []).map(entry => ({
        id: entry.id,
        entry_number: entry.entry_number,
        entry_date: entry.entry_date,
        competence_date: entry.competence_date,
        description: entry.description,
        history: entry.history,
        document_number: entry.document_number,
        document_type: entry.document_type,
        entry_type: entry.entry_type,
        total_debit: Number(entry.total_debit || 0),
        total_credit: Number(entry.total_credit || 0),
        balanced: entry.balanced,
        ai_generated: entry.ai_generated || false,
        ai_confidence: entry.ai_confidence ? Number(entry.ai_confidence) : null,
        ai_model: entry.ai_model,
        internal_code: entry.internal_code,
        reference_type: entry.reference_type,
        reference_id: entry.reference_id,
        created_at: entry.created_at,
        lines: (entry.accounting_entry_items as any[] || []).map(line => ({
          id: line.id,
          account_id: line.account_id,
          account_code: line.chart_of_accounts?.code || '',
          account_name: line.chart_of_accounts?.name || '',
          debit: Number(line.debit || 0),
          credit: Number(line.credit || 0),
          description: line.description,
        })),
      }));

      setEntries(formattedEntries);

      // Calcular estatísticas
      const autoCount = formattedEntries.filter(e => e.ai_generated).length;
      setStats({
        total: formattedEntries.length,
        autoGenerated: autoCount,
        manual: formattedEntries.length - autoCount,
        totalDebit: formattedEntries.reduce((sum, e) => sum + e.total_debit, 0),
        totalCredit: formattedEntries.reduce((sum, e) => sum + e.total_credit, 0),
      });

    } catch (error: any) {
      console.error("Erro:", error);
      toast.error("Erro ao carregar lançamentos", { description: error.message });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadEntries();
    loadChartOfAccounts();
  }, [selectedYear, selectedMonth]);

  // Filtrar por busca e origem
  const filteredEntries = useMemo(() => {
    let result = entries;

    // Filtro de origem
    if (filterOrigin === 'auto') {
      result = result.filter(e => e.ai_generated);
    } else if (filterOrigin === 'manual') {
      result = result.filter(e => !e.ai_generated);
    }

    // Busca textual
    if (searchTerm) {
      const search = searchTerm.toLowerCase();
      const searchNum = parseFloat(searchTerm.replace(/[^\d.,]/g, '').replace(',', '.'));
      result = result.filter(e =>
        e.description?.toLowerCase().includes(search) ||
        e.document_number?.toLowerCase().includes(search) ||
        e.internal_code?.toLowerCase().includes(search) ||
        e.lines.some(l =>
          l.account_code.includes(search) ||
          l.account_name.toLowerCase().includes(search) ||
          (l.debit === searchNum || l.credit === searchNum) ||
          (Math.abs(l.debit - searchNum) < 0.01 || Math.abs(l.credit - searchNum) < 0.01)
        )
      );
    }

    return result;
  }, [entries, filterOrigin, searchTerm]);

  const toggleExpand = (id: string) => {
    const newSet = new Set(expandedEntries);
    if (newSet.has(id)) {
      newSet.delete(id);
    } else {
      newSet.add(id);
    }
    setExpandedEntries(newSet);
  };

  const toggleSelect = (id: string) => {
    const newSet = new Set(selectedEntries);
    if (newSet.has(id)) {
      newSet.delete(id);
    } else {
      newSet.add(id);
    }
    setSelectedEntries(newSet);
  };

  const selectAll = () => {
    if (selectedEntries.size === filteredEntries.length) {
      setSelectedEntries(new Set());
    } else {
      setSelectedEntries(new Set(filteredEntries.map(e => e.id)));
    }
  };

  // Edição de linha
  const handleEditLine = (entry: AccountingEntry, line: AccountingEntry['lines'][0]) => {
    setEditingLine({
      entry_id: entry.id,
      line_id: line.id,
      account_code: line.account_code,
      account_name: line.account_name,
      account_id: line.account_id,
      debit: line.debit,
      credit: line.credit,
      description: line.description,
    });
    setEditDialogOpen(true);
  };

  const handleSaveEdit = async () => {
    if (!editingLine) return;

    try {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user?.id) throw new Error('Usuário não identificado');

      const updates: Record<string, any> = {};

      if (editingLine.account_code) {
        const account = chartOfAccounts.find(a => a.code === editingLine.account_code);
        if (account) {
          updates.account_id = account.id;
        }
      }

      if (editingLine.debit >= 0) {
        updates.debit = editingLine.debit;
      }

      if (editingLine.credit >= 0) {
        updates.credit = editingLine.credit;
      }

      if (Object.keys(updates).length === 0) {
        toast.error('Nenhuma alteração foi feita');
        return;
      }

      const { error: updateError } = await supabase
        .from('accounting_entry_items')
        .update(updates)
        .eq('id', editingLine.line_id);

      if (updateError) {
        throw new Error(`Erro ao atualizar: ${updateError.message}`);
      }

      await AccountingAuditService.logLineChange(
        editingLine.entry_id,
        editingLine.line_id,
        {
          line_id: editingLine.line_id,
          old_account_code: editingLine.account_code,
          new_account_code: editingLine.account_code,
          old_debit: editingLine.debit,
          new_debit: updates.debit !== undefined ? updates.debit : editingLine.debit,
          old_credit: editingLine.credit,
          new_credit: updates.credit !== undefined ? updates.credit : editingLine.credit
        },
        user.user.id
      );

      toast.success('Lançamento atualizado com sucesso!');
      setEditDialogOpen(false);
      setEditingLine(null);
      loadEntries();
    } catch (error: any) {
      console.error('Erro ao salvar edição:', error?.message || error);
      toast.error(`Erro ao atualizar lançamento: ${error?.message || 'Erro desconhecido'}`);
    }
  };

  // Histórico de auditoria
  const handleShowHistory = async (entryId: string) => {
    try {
      setSelectedEntryId(entryId);
      const history = await AccountingAuditService.getEntryAuditHistory(entryId);
      setAuditHistory(history);
      setHistoryDialogOpen(true);
    } catch (error: any) {
      console.error('Erro ao carregar histórico:', error?.message || error);
      toast.error(`Erro ao carregar histórico: ${error?.message || 'Erro desconhecido'}`);
    }
  };

  // Exclusão
  const deleteSelected = async () => {
    if (selectedEntries.size === 0) return;

    if (!confirm(`Deseja excluir ${selectedEntries.size} lançamento(s)? Uma entrada de auditoria será registrada.`)) return;

    try {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user?.id) throw new Error('Usuário não identificado');

      // Deletar com auditoria
      for (const entryId of selectedEntries) {
        await AccountingAuditService.deleteEntryWithAudit(
          entryId,
          user.user.id,
          'Deletado pelo usuário via Livro Diário'
        );
      }

      // Atualizar bank_transactions que referenciavam esses lançamentos
      await supabase
        .from('bank_transactions')
        .update({ matched: false, journal_entry_id: null })
        .in('journal_entry_id', Array.from(selectedEntries));

      toast.success(`${selectedEntries.size} lançamento(s) excluído(s)`);
      setSelectedEntries(new Set());
      loadEntries();
    } catch (error: any) {
      toast.error("Erro ao excluir", { description: error.message });
    }
  };

  const exportToCSV = () => {
    const headers = ['Data', 'Número', 'Descrição', 'Conta', 'Débito', 'Crédito', 'Tipo', 'AI', 'Confiança'];
    const rows: any[] = [];

    filteredEntries.forEach(e => {
      e.lines.forEach(line => {
        rows.push([
          format(parseISO(e.entry_date), 'dd/MM/yyyy'),
          e.entry_number,
          `"${e.description.replace(/"/g, '""')}"`,
          `${line.account_code} - ${line.account_name}`,
          line.debit.toFixed(2),
          line.credit.toFixed(2),
          e.entry_type,
          e.ai_generated ? 'Sim' : 'Não',
          e.ai_confidence ? `${(e.ai_confidence * 100).toFixed(0)}%` : '-',
        ]);
      });
    });

    const csv = [headers.join(';'), ...rows.map(r => r.join(';'))].join('\n');
    const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `livro_diario_${format(new Date(), 'yyyy-MM-dd')}.csv`;
    a.click();
  };

  if (loading) {
    return (
      <Layout>
        <div className="flex items-center justify-center min-h-[60vh]">
          <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-primary" />
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="space-y-4 sm:space-y-6 p-4 sm:p-6">
        {/* Header */}
        <div>
          <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold">
            Livro Diário
          </h1>
          <p className="text-xs sm:text-sm text-muted-foreground mt-1">
            Registro cronológico de todos os lançamentos contábeis
          </p>
        </div>

        <PeriodFilter />

        {/* Stats Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
          <Card className="p-3 sm:p-4">
            <div className="text-xs text-muted-foreground">Total</div>
            <div className="text-xl sm:text-2xl font-bold">{stats.total}</div>
          </Card>
          <Card className="p-3 sm:p-4 bg-purple-50 border-purple-200">
            <div className="text-xs text-muted-foreground flex items-center gap-1">
              <Bot className="h-3 w-3 text-purple-600" /> Automáticos
            </div>
            <div className="text-xl sm:text-2xl font-bold text-purple-600">{stats.autoGenerated}</div>
          </Card>
          <Card className="p-3 sm:p-4 bg-blue-50 border-blue-200">
            <div className="text-xs text-muted-foreground flex items-center gap-1">
              <User className="h-3 w-3 text-blue-600" /> Manuais
            </div>
            <div className="text-xl sm:text-2xl font-bold text-blue-600">{stats.manual}</div>
          </Card>
          <Card className="p-3 sm:p-4 bg-green-50 border-green-200">
            <div className="text-xs text-muted-foreground">Total Débitos</div>
            <div className="text-lg sm:text-xl font-bold text-green-600">{formatCurrency(stats.totalDebit)}</div>
          </Card>
          <Card className="p-3 sm:p-4 bg-red-50 border-red-200">
            <div className="text-xs text-muted-foreground">Total Créditos</div>
            <div className="text-lg sm:text-xl font-bold text-red-600">{formatCurrency(stats.totalCredit)}</div>
          </Card>
        </div>

        {/* Filters & Actions */}
        <Card>
          <CardContent className="p-4">
            <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
              <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
                {/* Busca */}
                <div className="relative flex-1 sm:flex-none sm:w-[300px]">
                  <Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder="Buscar descrição, documento, conta, valor..."
                    className="pl-9 h-9"
                    value={searchTerm}
                    onChange={e => setSearchTerm(e.target.value)}
                  />
                </div>

                {/* Filtro de origem */}
                <Select value={filterOrigin} onValueChange={(v: any) => setFilterOrigin(v)}>
                  <SelectTrigger className="h-9 w-full sm:w-[150px]">
                    <SelectValue placeholder="Origem" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Todos</SelectItem>
                    <SelectItem value="auto">
                      <span className="flex items-center gap-1">
                        <Sparkles className="h-3 w-3 text-purple-600" /> Automáticos
                      </span>
                    </SelectItem>
                    <SelectItem value="manual">
                      <span className="flex items-center gap-1">
                        <User className="h-3 w-3" /> Manuais
                      </span>
                    </SelectItem>
                  </SelectContent>
                </Select>

                {searchTerm && (
                  <Button variant="ghost" size="sm" onClick={() => setSearchTerm('')}>
                    <X className="h-4 w-4 mr-1" /> Limpar
                  </Button>
                )}
              </div>

              <div className="flex gap-2 w-full sm:w-auto justify-end">
                {selectedEntries.size > 0 && (
                  <Button variant="destructive" size="sm" onClick={deleteSelected}>
                    <Trash2 className="h-4 w-4 mr-1" />
                    Excluir ({selectedEntries.size})
                  </Button>
                )}
                <Button variant="outline" size="sm" onClick={exportToCSV}>
                  <FileDown className="h-4 w-4 mr-1" />
                  Exportar
                </Button>
                <Button variant="outline" size="sm" onClick={loadEntries} disabled={loading}>
                  <RefreshCw className={cn("h-4 w-4 mr-1", loading && "animate-spin")} />
                  Atualizar
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Table */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">
              Lançamentos do Período
            </CardTitle>
            <CardDescription>
              {filteredEntries.length} lançamentos encontrados
            </CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            <ScrollArea className="h-[calc(100vh-500px)] min-h-[400px]">
              <Table>
                <TableHeader className="sticky top-0 bg-background z-10">
                  <TableRow>
                    <TableHead className="w-[40px]">
                      <Checkbox
                        checked={selectedEntries.size === filteredEntries.length && filteredEntries.length > 0}
                        onCheckedChange={selectAll}
                      />
                    </TableHead>
                    <TableHead className="w-[40px]"></TableHead>
                    <TableHead className="w-[100px]">Data</TableHead>
                    <TableHead className="w-[60px]">Nº</TableHead>
                    <TableHead>Descrição</TableHead>
                    <TableHead className="w-[120px] text-right">Débito</TableHead>
                    <TableHead className="w-[120px] text-right">Crédito</TableHead>
                    <TableHead className="w-[100px] text-center">Ações</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredEntries.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={8} className="text-center py-8 text-muted-foreground">
                        Nenhum lançamento encontrado para o período selecionado
                      </TableCell>
                    </TableRow>
                  ) : (
                    filteredEntries.map(entry => (
                      <>
                        <TableRow
                          key={entry.id}
                          className={cn(
                            "cursor-pointer hover:bg-muted/50",
                            selectedEntries.has(entry.id) && "bg-blue-50",
                            expandedEntries.has(entry.id) && "bg-muted/30"
                          )}
                          onClick={() => toggleExpand(entry.id)}
                        >
                          <TableCell onClick={e => e.stopPropagation()}>
                            <Checkbox
                              checked={selectedEntries.has(entry.id)}
                              onCheckedChange={() => toggleSelect(entry.id)}
                            />
                          </TableCell>
                          <TableCell>
                            <Button variant="ghost" size="sm" className="h-6 w-6 p-0">
                              {expandedEntries.has(entry.id) ? (
                                <ChevronDown className="h-4 w-4" />
                              ) : (
                                <ChevronRight className="h-4 w-4" />
                              )}
                            </Button>
                          </TableCell>
                          <TableCell className="font-mono text-sm">
                            {format(parseISO(entry.entry_date), 'dd/MM/yyyy')}
                          </TableCell>
                          <TableCell className="text-muted-foreground text-sm">
                            {entry.entry_number}
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-2">
                              <span className="truncate max-w-[250px] sm:max-w-[400px]" title={entry.description}>
                                {entry.description}
                              </span>
                              {entry.ai_generated && (
                                <Badge variant="secondary" className="bg-purple-100 text-purple-700 text-[10px] px-1.5 shrink-0">
                                  <Sparkles className="h-3 w-3 mr-0.5" />
                                  {entry.ai_confidence ? `${(entry.ai_confidence * 100).toFixed(0)}%` : 'AI'}
                                </Badge>
                              )}
                              {!entry.balanced && (
                                <Badge variant="destructive" className="text-[10px] px-1.5 shrink-0">
                                  <AlertTriangle className="h-3 w-3 mr-0.5" />
                                  Desbalanceado
                                </Badge>
                              )}
                            </div>
                          </TableCell>
                          <TableCell className="text-right font-mono text-green-600">
                            {formatCurrency(entry.total_debit)}
                          </TableCell>
                          <TableCell className="text-right font-mono text-red-600">
                            {formatCurrency(entry.total_credit)}
                          </TableCell>
                          <TableCell className="text-center" onClick={e => e.stopPropagation()}>
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => handleShowHistory(entry.id)}
                              className="h-7 w-7 p-0"
                              title="Histórico"
                            >
                              <History className="h-4 w-4" />
                            </Button>
                          </TableCell>
                        </TableRow>

                        {/* Linhas expandidas */}
                        {expandedEntries.has(entry.id) && (
                          <TableRow className="bg-muted/20">
                            <TableCell colSpan={8} className="p-0">
                              <div className="p-4 space-y-3">
                                {/* Metadata */}
                                <div className="flex flex-wrap gap-3 text-xs text-muted-foreground">
                                  {entry.internal_code && (
                                    <span>Código: <code className="bg-muted px-1 rounded">{entry.internal_code}</code></span>
                                  )}
                                  {entry.document_number && (
                                    <span>Doc: {entry.document_number}</span>
                                  )}
                                  {entry.ai_model && (
                                    <span>Modelo: {entry.ai_model}</span>
                                  )}
                                  <span>Criado: {format(parseISO(entry.created_at), 'dd/MM/yyyy HH:mm')}</span>
                                </div>

                                {/* Entry lines */}
                                <div className="bg-white rounded-lg border">
                                  <Table>
                                    <TableHeader>
                                      <TableRow className="text-xs">
                                        <TableHead className="py-2 w-[100px]">Conta</TableHead>
                                        <TableHead className="py-2">Nome</TableHead>
                                        <TableHead className="py-2 text-right w-[120px]">Débito</TableHead>
                                        <TableHead className="py-2 text-right w-[120px]">Crédito</TableHead>
                                        <TableHead className="py-2 text-center w-[60px]">Ações</TableHead>
                                      </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                      {entry.lines.map(line => (
                                        <TableRow key={line.id} className="text-sm">
                                          <TableCell className="py-2 font-mono text-xs">{line.account_code}</TableCell>
                                          <TableCell className="py-2">{line.account_name}</TableCell>
                                          <TableCell className="py-2 text-right font-mono text-green-600">
                                            {line.debit > 0 ? formatCurrency(line.debit) : '-'}
                                          </TableCell>
                                          <TableCell className="py-2 text-right font-mono text-red-600">
                                            {line.credit > 0 ? formatCurrency(line.credit) : '-'}
                                          </TableCell>
                                          <TableCell className="py-2 text-center">
                                            <Button
                                              size="sm"
                                              variant="ghost"
                                              onClick={() => handleEditLine(entry, line)}
                                              className="h-6 w-6 p-0"
                                              title="Editar linha"
                                            >
                                              <Edit2 className="h-3 w-3" />
                                            </Button>
                                          </TableCell>
                                        </TableRow>
                                      ))}
                                      <TableRow className="bg-muted/50 font-semibold">
                                        <TableCell colSpan={2} className="py-2">Total</TableCell>
                                        <TableCell className="py-2 text-right font-mono">{formatCurrency(entry.total_debit)}</TableCell>
                                        <TableCell className="py-2 text-right font-mono">{formatCurrency(entry.total_credit)}</TableCell>
                                        <TableCell></TableCell>
                                      </TableRow>
                                    </TableBody>
                                  </Table>
                                </div>
                              </div>
                            </TableCell>
                          </TableRow>
                        )}
                      </>
                    ))
                  )}
                </TableBody>
              </Table>
            </ScrollArea>
          </CardContent>
        </Card>

        {/* Dialog de Edição */}
        <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Editar Lançamento</DialogTitle>
              <DialogDescription>
                Altere a conta e valores conforme necessário
              </DialogDescription>
            </DialogHeader>
            {editingLine && (
              <div className="space-y-4">
                <div>
                  <Label htmlFor="edit-account">Conta</Label>
                  <select
                    id="edit-account"
                    className="w-full px-3 py-2 border border-input rounded-md bg-background"
                    value={editingLine.account_code}
                    onChange={(e) => {
                      const account = chartOfAccounts.find(a => a.code === e.target.value);
                      setEditingLine(prev => prev ? {
                        ...prev,
                        account_code: e.target.value,
                        account_name: account?.name || prev.account_name,
                        account_id: account?.id || prev.account_id
                      } : null);
                    }}
                  >
                    {chartOfAccounts.map(account => (
                      <option key={account.id} value={account.code}>
                        {account.code} - {account.name}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <Label htmlFor="edit-debit">Débito</Label>
                  <Input
                    id="edit-debit"
                    type="number"
                    step="0.01"
                    value={editingLine.debit}
                    onChange={(e) => setEditingLine(prev => prev ? {
                      ...prev,
                      debit: parseFloat(e.target.value) || 0
                    } : null)}
                  />
                </div>
                <div>
                  <Label htmlFor="edit-credit">Crédito</Label>
                  <Input
                    id="edit-credit"
                    type="number"
                    step="0.01"
                    value={editingLine.credit}
                    onChange={(e) => setEditingLine(prev => prev ? {
                      ...prev,
                      credit: parseFloat(e.target.value) || 0
                    } : null)}
                  />
                </div>
              </div>
            )}
            <DialogFooter>
              <Button variant="outline" onClick={() => setEditDialogOpen(false)}>
                Cancelar
              </Button>
              <Button onClick={handleSaveEdit}>
                Salvar Alterações
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Dialog de Histórico */}
        <Dialog open={historyDialogOpen} onOpenChange={setHistoryDialogOpen}>
          <DialogContent className="max-w-2xl max-h-[80vh]">
            <DialogHeader>
              <DialogTitle>Histórico de Alterações</DialogTitle>
              <DialogDescription>
                Todas as mudanças registradas para este lançamento
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 overflow-y-auto max-h-[60vh]">
              {auditHistory.length === 0 ? (
                <p className="text-sm text-muted-foreground text-center py-4">Nenhuma alteração registrada</p>
              ) : (
                auditHistory.map((log) => (
                  <div key={log.id} className="border rounded-lg p-4 space-y-2">
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="font-medium text-sm">
                          {log.action === 'update' ? '✏️ Alterado' : log.action === 'delete' ? '🗑️ Deletado' : '📝 Criado'}
                        </p>
                        <p className="text-xs text-muted-foreground">
                          {new Date(log.created_at).toLocaleString('pt-BR')}
                        </p>
                      </div>
                      <Badge variant="outline">
                        {log.user?.email || 'Sistema'}
                      </Badge>
                    </div>
                    {log.metadata?.change_description && (
                      <p className="text-sm text-muted-foreground">
                        {log.metadata.change_description}
                      </p>
                    )}
                    {log.old_values && log.new_values && (
                      <div className="text-xs space-y-1 bg-muted p-2 rounded">
                        {Object.keys(log.new_values).map(key => (
                          log.old_values[key] !== log.new_values[key] && (
                            <div key={key}>
                              <span className="font-mono">
                                {key}: {JSON.stringify(log.old_values[key])} → {JSON.stringify(log.new_values[key])}
                              </span>
                            </div>
                          )
                        ))}
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          </DialogContent>
        </Dialog>
      </div>
    </Layout>
  );
};

export default LivroDiario;
