ALTER TABLE clients
ADD COLUMN IF NOT EXISTS is_pro_bono BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS pro_bono_start_date DATE,
ADD COLUMN IF NOT EXISTS pro_bono_end_date DATE,
ADD COLUMN IF NOT EXISTS pro_bono_reason TEXT;
