// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { customFetch } from '@/lib/customFetch';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const resolvedSupabaseUrl =
  SUPABASE_URL && SUPABASE_URL.length > 0
    ? SUPABASE_URL
    : SUPABASE_PROJECT_ID && SUPABASE_PROJECT_ID.length > 0
      ? `https://${SUPABASE_PROJECT_ID}.supabase.co`
      : undefined;

if (!resolvedSupabaseUrl) {
  throw new Error("Supabase URL is not configured. Set VITE_SUPABASE_URL or provide VITE_SUPABASE_PROJECT_ID.");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase publishable key is not configured. Set VITE_SUPABASE_PUBLISHABLE_KEY.");
}

// Create a resilient fetch wrapper with retry logic
const resilientFetch: typeof fetch = async (input, init) => {
  const maxRetries = 3;
  let lastError: any = null;

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      // Try native fetch first (which is patched by patchFetchForVitePing but eventually calls native fetch)
      const response = await Promise.race([
        fetch(input as RequestInfo, init),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error("Fetch timeout after 30s")), 30000)
        ),
      ]);
      return response as Response;
    } catch (error) {
      lastError = error;
      const errorMsg = error instanceof Error ? error.message : String(error);

      if (attempt < maxRetries - 1) {
        const delayMs = Math.pow(2, attempt) * 1000;
        console.warn(`[Supabase] Fetch attempt ${attempt + 1} failed, retrying in ${delayMs}ms`, {
          url: String(input),
          error: errorMsg,
        });
        await new Promise(resolve => setTimeout(resolve, delayMs));
      } else {
        console.warn("[Supabase] Native fetch failed after retries, attempting fallback to customFetch (XHR)", {
          url: String(input),
          error: errorMsg,
        });

        try {
          return await customFetch(input, init);
        } catch (xhrError) {
          const xhrErrorMsg = xhrError instanceof Error ? xhrError.message : String(xhrError);
          console.error("[Supabase] CustomFetch (XHR) fallback also failed", {
            url: String(input),
            fetchError: errorMsg,
            xhrError: xhrErrorMsg,
          });
          throw lastError;
        }
      }
    }
  }

  throw lastError;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(resolvedSupabaseUrl, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: resilientFetch,
  }
});
